# NREL API key for PVWatts V8 (developer.nrel.gov/signup/)
NREL_API_KEY = "PzxMvoJ4JxAhYApp2DQADehiDvnQiHZUFkX0QEyr"

# AWS credentials for S3 access
AWS_ACCESS_KEY_ID = "AKIAYQYUAPZPTLWPWM46"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "eu-west-1"
